config/routes.rb
Rails.application.routes.draw do
  root 'articles#welcome'
  devise_for :users
  devise_for :installs
  # IF installs is not needed, you can also remove it here
  resources :cars
  # root to: 'article#index'

      resources :articles do
        resources :comments
    end
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :comments, dependent: :destroy
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :articles
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/install.rb
class Install < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles
  has_many :cars
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

#welcome

def welcome
@articles = Article.all
@cars = Car.all
end

  # index
  def index
    if params[:category].blank?
    @articles = Article.all
    else
      category_id = Category.find_by(name: params[:category]).id
      @articles = Article.where(:category_id => category_id).order("created_at DESC")
    end
    # Really good use of query parameters
    # Try to make sure indentation is uniform and clear
  end

  # new
  def new
    @article = current_user.articles.create
    @categories = Category.all.map {|c| [c.name, c.id]}
    # Perfect use here of .map
  end

  # create
  def create
  		@article = current_user.articles.build(article_params)
  		@article.category_id = (params[:category_id])

  		if @article.save
  			redirect_to root_path
  		else
  			render 'new'
  		end
  	end

  #show
  def show
    @article = Article.find(params[:id])
  end

  # edit
  def edit
    @categories = Category.all.map {|c| [c.name, c.id]}
    @article = Article.find(params[:id])
  end

# update
  def update
    @article = Article.find(params[:id])
    @article.category_id = (params[:category_id])

    if @article.user == current_user
      @article.update(article_params)

    else
      flash[:alert] = "Only the author of the article can Update"
    end


    redirect_to article_path(@article)
  end

  # destroy
  def destroy
    @article = Article.find(params[:id])
    if @article.user == current_user
      @article.destroy
    else
      flash[:alert] = "Only the author of the article can delete"
    end
    redirect_to articles_path
  end


  private
  def article_params
    params.require(:article).permit(:title, :body, :photo_url, :author_name, :category_id)
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy]
  # While I see that you are trying to use before_action to make your code more DRY,
  # for readability, I would just repeat the
  #
  #   @car = Car.find(params[:id])
  #
  # code block in each one of those methods


  # Also, it looks like you used rails g controller to make this file. While that is
  # acceptable, you need to go clean out all of the unneccessary code comments /
  # code that it generated as well (such as the render json methods, unused .coffee
  # files in javascripts, and the unused .json_builder files in views). Also make sure
  # you read through all of your code and understand anything that the generator set up
  # for you.

  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.all
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = current_user.cars.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = current_user.cars.create!(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    @cars = Car.find(params[:id])
    if @cars.user == current_user
      @cars.update(car_params)
    else
      flash[:alert] = "Only the author of the cars can Update"
    end
    redirect_to cars_path
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @cars = Car.find(params[:id])
    if @cars.user == current_user
      @cars.destroy
    else
      flash[:alert] = "Only the author of the cars can delete"
    end
    redirect_to cars_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:title, :body, :make, :model, :year, :price, :seller_name, :seller_phone, :photo_url)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  # new
  def index
    @comments = Comment.all
  end

  def new
    @article = Article.find(params[:article_id])
    @comment = @article.comments.new
  end

  # create
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create!(comment_params)

    redirect_to article_path(@article)
  end

  #show
  def show
    @comment = Comment.find(params[:id])
  end

  # edit
  def edit
    @article = Article.find(params[:article_id])
    @comment = Comment.find(params[:id])
  end

  # update
  def update
    @article = Article.find(params[:article_id])
    @comment = Comment.find(params[:id])
    @comment.update(comment_params)

    redirect_to article_comment_path(@article, @comment)
  end

  # destroy
  def destroy
    @comment = Comment.find(params[:id]).destroy

    redirect_to article_path(@comment.article)
  end

  private
  def comment_params
    params.require(:comment).permit(:body, :author_name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/articles/edit.html.erb
<h2 class="article-edit-title">Submit Your Story</h2>
<div class="article-edit-container">
  <%= form_for @article, :html => {:multipart => true} do |f| %>
  <div class="form-wrapper">

    <div class="form-row">
      <%= f.label :title, class:"label"%>
      <%= f.text_field :title, class:"text_field"%>
    </div>

    <div class="form-row">
      <%= f.label :body,  class:"label"%>
      <%= f.text_field :body, class:"text_field" %>
    </div>

    <div class="form-row">
      <%= f.label :author_name, class:"label" %>
      <%= f.text_field :author_name, class:"text_field" %>
    </div>
    <div class="form-row">
      <%= f.label :photo_url, class:"label" %>
      <%= f.text_field :photo_url, class:"text_field"%>
    </div>
    <div class="form-row">
      <%= f.submit %>
      <% end %>
      <div class="form-row">
        <%= form_for @article, method: :delete do |f|%>
        <%= f.submit "Delete!", class: "delete" %>
      </div>

      <div class="form-row">
      <%= f.select :category_id, @categories%>
      </div>

    </div>

    <% end %>
  </div>

app/views/articles/index.html.erb
<h1 class="title"><%= params[:category]%></h1>


<%if @articles.count == 0 %>
<p>There are no cars in this category</p>

<%end%>

<div class="article-index-container">
  <%@articles.each do |article| %>
  <div class="index-photo">
    <%= image_tag article.photo_url, class:"article-index-photo"%>
    <p class="article-title"><%= link_to article.title, article %></p>
  </div>
  <% end %>
</div>

<%if user_signed_in?%>

<div class="submit">

  <%= link_to "Share a Story", new_article_path, class:"all-buttons hvr-fade"%>
</div>

<%end%>

app/views/articles/new.html.erb
<h2 class="title">New Article</h2>

<%= form_for @article do |f| %>
<div class="form-wrapper">

  <div class="form-row">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>


  <div class="form-row">
    <%= f.label :body %>
    <%= f.text_field :body %>
  </div>


  <div class="form-row">
    <%= f.label :photo_url %>
    <%= f.text_field :photo_url %>
  </div>

  <div class="form-row">
    <%= f.label :author_name %>
    <%= f.text_field :author_name %>
  </div>


  <div class="form-row">
    <%= select_tag(:category_id, options_for_select(@categories), :prompt => "Select a category") %>
  </div>

  <div class="form-row">
    <%= f.submit %>
  </div>
</div>
<% end %>

app/views/articles/show.html.erb
<div class="show-wrapper">
  <h1 class="title"><%= @article.title %>
  </h2>

  <p class="by">By: <%=@article.author_name%></p>
  <p class="by">Section: <%=@article.category.name%></p>
  <p class="by">Created: <%=@article.created_at%></p>

  <div class="article-phot">

    <%= image_tag @article.photo_url, class: "article-show-photo" %>
    <p class="article-show-p"><%= @article.body%></p>

  </div>

  <!-- <%= image_tag @article.photo_url, class: "article-show-photo" %>
  <h3 class="article-show-edit"><%= link_to "Edit Article", edit_article_path(@article) %></h3> -->

  <% @article.comments.each do |comment| %>
  <p class="comment-container"><%= link_to "#{comment.body} By: #{comment.author_name}", article_comment_path(@article, comment), class:"comment"%></p><br>
  <% end %>
  <h3 class="all-buttons hvr-fade"><%= link_to "Write a comment", new_article_comment_path(@article) %></h3>

  <%if @article.user == current_user && user_signed_in?%>
      <h3 class="all-buttons hvr-fade"><%= link_to "Edit Article", edit_article_path(@article) %></h3>

  <%  end %>





</div>

app/views/articles/welcome.html.erb
<%# You don't need to rewrite the boilerplate here (html, head, etc) because this whole
file is going to be rendered within the yield in layouts/application.html.erb %>
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <div class="welcome">

      <div class="welcome-logo">
        <img src="http://i.imgur.com/0qdjhbR.png"/>
      </div>

      <div class="welcome-img">
        <img src="http://files1.porsche.com/filestore/image/multimedia/none/rd-2014-porscheclassic-models-roadvehicles-911g-teaser/normal/8144464b-f0f0-11e5-84b6-0019999cd470/porsche-normal.jpg">
      </div>

    </div>
<hr>
    <div class="article-index-container">
      <%if @articles.count == 0 %>
      <p class="category-notice">There are no cars in this category</p>
      <%end%>
      <%@articles.each do |article| %>

      <div class="index-photo">
        <%= image_tag article.photo_url, class:"article-index-photo"%>
        <p class="article-title"><%= link_to article.title, article %></p>

      </div>

      <% end %>

    </div>

  </div>

</body>
</html>

app/views/cars/_form.html.erb
<div class="form-wrapper">
<%= form_for(car) do |f| %>

  <div class="form-row">
    <%= f.label :title, class:"label" %>
    <%= f.text_field :title %>
  </div>

  <div class="form-row">
    <%= f.label :body, class:"label" %>
    <%= f.text_area :body, class:"text_area" %>
  </div>

  <div class="form-row">
  <%= f.label :make, class:"label" %>
  <%= f.text_field :make %>
  </div>

  <div class="form-row">
    <%= f.label :model,class:"label" %>
    <%= f.text_field :model %>
  </div>

  <div class="form-row">
    <%= f.label :year,class:"label" %>
    <%= f.number_field :year %>
  </div>

  <div class="form-row">
    <%= f.label :price, class:"label" %>
    <%= f.text_field :price %>
  </div>

  <div class="form-row">
    <%= f.label :seller_name, class:"label" %>
    <%= f.text_field :seller_name %>
  </div>

  <div class="form-row">
    <%= f.label :seller_phone, class:"label" %>
    <%= f.text_field :seller_phone %>
  </div>

  <div class="form-row">
    <%= f.label :photo_url, class:"label" %>
    <%= f.text_field :photo_url %>
  </div>


    <%= f.submit %>


<% end %>
</div>

app/views/cars/edit.html.erb
<h1>Editing Car</h1>

<%= render 'form', car: @car %>
<div class="show-back">

  <%= link_to 'Show', @car, class:"nav-content hvr-fade" %> |
  <%= link_to 'Back', cars_path, class:"nav-content hvr-fade" %>
</div>

app/views/cars/index.html.erb
<div class="car-ad-wraper">
  <h1 class="title">Classics for sale</h1>

  <% @cars.each do |car| %>

  <div class="car-ad-upper">
    <div class="car-ad-img"><%= image_tag car.photo_url%></div>
    <h1 class="title"><%= car.title%></h1>
  </div>

  <div class="car-ad-lower">

    <%= link_to 'Show', car, class:"all-buttons hvr-fade" %>

  </div>

  <% end %>

  <div class="">

    <% if current_user %>
    <%= link_to 'New Car', new_car_path, class:"all-buttons hvr-fade" %>
    <% end %>
  </div>
</div>

app/views/cars/new.html.erb
<h1 class="title">New Car</h1>

<%= render 'form', car: @car %>
<div class="car-new-div">
  <%= link_to 'Back', cars_path, class:"all-buttons hvr-fade" %>

</div>

app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>

<div class="car-show">

  <p class="title">
    <%= @car.title %>
  </p>

  <div class="car-info-container">

    <p class="car-info">
      <%= @car.make %>
    </p>

    <p class="car-info">
      <%= @car.model %>
    </p>

    <p class="car-info">
      <%= @car.year %>
    </p>

    <p class="car-info">
      <%= @car.price %>
    </p>

    <p class="car-info">
      <%= @car.seller_name %>
    </p>

    <p class="car-info">
      <%= @car.seller_phone %>
    </p>
  </div>

  <div class="car-show-phot">
    <%= image_tag @car.photo_url, class:"for-sale"%>
  </div>

  <p class="ad">
    <%= @car.body%>
  </p>


<div car-show-buttons>
    <%if @car.user == current_user && user_signed_in?%>
    <%= link_to 'Delete', @car, method: :delete, data: { confirm: 'Are you sure?' }, class: "all-buttons hvr-fade"%>

    <%= link_to 'Edit', edit_car_path(@car), class: "all-buttons hvr-fade" %>

    <%  end %>

    <%= link_to 'Back', cars_path, class:"all-buttons hvr-fade" %>

  </div>

</div>

app/views/comments/edit.html.erb
<h2 class="title">Edit comment</h2>

<%= form_for [@article, @comment] do |f| %>
<div class="form-wrapper">

<div class="form-row">
  <%= f.label :body %>
  <%= f.text_field :body %>
</div>

<div class="form-row">
  <%= f.label :author_name %>
  <%= f.text_field :author_name %>
</div>


<div class="form-row">
    <%= f.submit %>
</div>

<% end %>
<div class="form-row">
  <%= form_for [@article, @comment], method: :delete do |f| %>
    <%= f.submit "Delete!", class: "delete" %>


</div>
  <% end %>
</div>

app/views/comments/index.html.erb
<h2 class="title">Comments</h2>
<h2><%= link_to "ad comment", new_article_comment_path %></h2>


  <% @comments.each do |comment| %>

      <h2><<%=comment.body%></h2>
      <h2></h2>
  <% end %>

app/views/comments/new.html.erb
<h2 class="title">Share you story</h2>

<%= form_for [@article, @comment] do |f| %>
<div class="form-wraper">
  <div class="form-row">

    <%= f.label :body %>
    <%= f.text_field :body %>

  </div>

  <div class="form-row">

    <%= f.label :author_name %>
    <%= f.text_field :author_name %>

  </div>

  <div class="form-row">

    <%= f.submit %>
    <% end %>

  </div>

</div>

app/views/comments/show.html.erb
<div class="comment-container-show">

  <h2 class="title"><%= @comment.body %><h2>
    <h2><%= @comment.author_name %><h2>
      <h3 ><%= link_to "Edit comment", edit_article_comment_path(@comment.article, @comment), class:"all-buttons hvr-fade white" %></h3>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DC Cars and Coffee</title>
    <!-- <link rel="icon" href="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcShXSzccjYqq9xrt_Xdw6MRhzarUanr-18tMiS7jJuroskH92pX"> -->
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Oswald" rel="stylesheet">
    <%# Nice use of external fonts %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>




    <nav class="navbar">
      <img src="http://i.imgur.com/9yoJJg7.png" class="nav-logo"/>
      <a href="#"></a>
      <a class="nav-content hvr-fade" <%= link_to "Home", root_path%></a>
      <a class="nav-content hvr-fade" <%= link_to "Cars for slae", cars_path%></a>

  <a class="nav-content hvr-fade" <%= link_to "Articles", articles_path%></a>

  <%Category.all.each do |category|%>
  <a>
    <%=link_to category.name, articles_path(category: category.name), class: "nav-content hvr-fade" %>
  </a>

  <%end%>

</a>
<a class="nav-content hvr-fade" <%= link_to "Sign Up", new_user_registration_path%></a>

<% if user_signed_in? %>
<a class="nav-content hvr-fade" <%= link_to "Sign Out", destroy_user_session_path, method: :delete%></a>

<%else%>
<a class="nav-content hvr-fade" <%= link_to "Log In", new_user_session_path%></a>
<%end%>
</nav>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>